version: '2.4'

services:
  cibuild:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - user=${USER}
        - uid=${USER_ID}
        - gid=${GROUP_ID}
        - cache=/home/${USER}/.cache
    environment:
      - GIT_COMMIT=${GIT_COMMIT}
      - JENKINS_BUILDING=${JENKINS_BUILDING}
    network_mode: host
    volumes:
      - ./:/home/${USER}/src:Z
      - ./build/libs:/home/${USER}/.minecraft/mods:Z
      - ./scripts/init:/home/${USER}/init:Z
      - cached:/home/${USER}/.cache:Z
    command: "clean build --stacktrace"

volumes:
  cached:
